# Generated by Django 4.2.3 on 2023-07-23 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.CharField(default='', editable=False, help_text='roomId', max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('roomName', models.CharField(blank=True, default='', help_text='roomName', max_length=255, null=True, verbose_name='Name')),
                ('roomPassword', models.CharField(blank=True, default='', help_text='roomPassword', max_length=255, null=True, verbose_name='Password')),
                ('roomData', models.JSONField(blank=True, default=dict, help_text='roomData', null=True, verbose_name='Data')),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='createdAt', null=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='updatedAt', null=True, verbose_name='Updated At')),
                ('roomProfiles', models.ManyToManyField(to='messenger.profile')),
            ],
        ),
    ]
